In [15]:
import pandas as pd
import matplotlib.pyplot as plt

In [27]:
df= pd.read_csv("patient_details.csv")
df

    patient_id          name   age  gender     city admission_date height_cm
0         P001           NaN  25.0       F   mumbai     15-01-2024       180
1         P002  Rahul Sharma  60.0       F    Delhi     16-01-2024       170
2         P003    Neha Singh  45.0       M   Mumbai     16-01-2024       150
3         P004    Neha Singh  60.0    Male  kolkata     15-01-2024       170
4         P005    Neha Singh  25.0    Male  kolkata     15-01-2024       180
..         ...           ...   ...     ...      ...            ...       ...
125       P006   Anita Verma  25.0       M   Mumbai     15-01-2024       150
126       P007    Neha Singh  25.0       F  kolkata     15-01-2024       150
127       P008     John Paul  60.0       F  Chennai     15-01-2024       160
128       P009           NaN  45.0       M   Mumbai     15-01-2024       150
129       P010  Rahul Sharma  60.0  Female  Chennai     16-01-2024       150

[130 rows x 7 columns]

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 130 entries, 0 to 129
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   patient_id      130 non-null    object
 1   name            107 non-null    object
 2   age             106 non-null    float64
 3   gender          130 non-null    object
 4   city            130 non-null    object
 5   admission_date  130 non-null    object
 6   height_cm       130 non-null    object
dtypes: float64(1), object(6)
memory usage: 7.2+ KB

In [5]:
df.describe()

              age
count  106.000000
mean    35.849057
std     21.015546
min     -5.000000
25%     25.000000
50%     30.000000
75%     60.000000
max     60.000000

In [6]:
df.head(5)

  patient_id          name   age gender     city admission_date height_cm
0       P001           NaN  25.0      F   mumbai     15-01-2024       180
1       P002  Rahul Sharma  60.0      F    Delhi     16-01-2024       170
2       P003    Neha Singh  45.0      M   Mumbai     16-01-2024       150
3       P004    Neha Singh  60.0   Male  kolkata     15-01-2024       170
4       P005    Neha Singh  25.0   Male  kolkata     15-01-2024       180

In [7]:
df.tail(5)

    patient_id          name   age  gender     city admission_date height_cm
125       P006   Anita Verma  25.0       M   Mumbai     15-01-2024       150
126       P007    Neha Singh  25.0       F  kolkata     15-01-2024       150
127       P008     John Paul  60.0       F  Chennai     15-01-2024       160
128       P009           NaN  45.0       M   Mumbai     15-01-2024       150
129       P010  Rahul Sharma  60.0  Female  Chennai     16-01-2024       150

In [8]:
df.shape

(130, 7)

In [17]:
df.size

910

In [18]:
df.isna()

     patient_id   name    age  gender   city  admission_date  height_cm
0         False   True  False   False  False           False      False
1         False  False  False   False  False           False      False
2         False  False  False   False  False           False      False
3         False  False  False   False  False           False      False
4         False  False  False   False  False           False      False
..          ...    ...    ...     ...    ...             ...        ...
125       False  False  False   False  False           False      False
126       False  False  False   False  False           False      False
127       False  False  False   False  False           False      False
128       False   True  False   False  False           False      False
129       False  False  False   False  False           False      False

[130 rows x 7 columns]

In [19]:
df.isna().sum()

patient_id         0
name              23
age               24
gender             0
city               0
admission_date     0
height_cm          0
dtype: int64

In [25]:
df["name"]=df["name"].fillna("X")
df

    patient_id          name   age  gender     city admission_date height_cm
0         P001             X  25.0       F   mumbai     15-01-2024       180
1         P002  Rahul Sharma  60.0       F    Delhi     16-01-2024       170
2         P003    Neha Singh  45.0       M   Mumbai     16-01-2024       150
3         P004    Neha Singh  60.0    Male  kolkata     15-01-2024       170
4         P005    Neha Singh  25.0    Male  kolkata     15-01-2024       180
..         ...           ...   ...     ...      ...            ...       ...
125       P006   Anita Verma  25.0       M   Mumbai     15-01-2024       150
126       P007    Neha Singh  25.0       F  kolkata     15-01-2024       150
127       P008     John Paul  60.0       F  Chennai     15-01-2024       160
128       P009             X  45.0       M   Mumbai     15-01-2024       150
129       P010  Rahul Sharma  60.0  Female  Chennai     16-01-2024       150

[130 rows x 7 columns]

In [28]:
df['age'].isna().sum()

np.int64(24)

In [29]:
df["age"]=df["age"].fillna(df["age"].mean())
df

    patient_id          name   age  gender     city admission_date height_cm
0         P001           NaN  25.0       F   mumbai     15-01-2024       180
1         P002  Rahul Sharma  60.0       F    Delhi     16-01-2024       170
2         P003    Neha Singh  45.0       M   Mumbai     16-01-2024       150
3         P004    Neha Singh  60.0    Male  kolkata     15-01-2024       170
4         P005    Neha Singh  25.0    Male  kolkata     15-01-2024       180
..         ...           ...   ...     ...      ...            ...       ...
125       P006   Anita Verma  25.0       M   Mumbai     15-01-2024       150
126       P007    Neha Singh  25.0       F  kolkata     15-01-2024       150
127       P008     John Paul  60.0       F  Chennai     15-01-2024       160
128       P009           NaN  45.0       M   Mumbai     15-01-2024       150
129       P010  Rahul Sharma  60.0  Female  Chennai     16-01-2024       150

[130 rows x 7 columns]

In [30]:
df.loc[df["patient_id"] == "P014", ["age"]]

          age
13  35.849057

In [31]:
df1=pd.read_csv("medical_records.csv")
df1

    record_id patient_id     diagnosis      bp  sugar_level  visit_cost
0        R101       P013  Hypertension  120/80        140.0        2000
1        R102       P105      Diabetes  120/80          NaN        2500
2        R103       P098  Hypertension    high        140.0        3000
3        R104       P038        Asthma  140/90          NaN        3000
4        R105       P040        Asthma  130/85          NaN        1500
..        ...        ...           ...     ...          ...         ...
115      R216       P081        Asthma    high        110.0        2500
116      R217       P033      Diabetes    high          NaN        1500
117      R218       P063  Hypertension  140/90          NaN        2000
118      R219       P011  Hypertension  130/85        180.0        2500
119      R220       P013  Hypertension    high        180.0        1500

[120 rows x 6 columns]

In [32]:
df1.isna()

     record_id  patient_id  diagnosis     bp  sugar_level  visit_cost
0        False       False      False  False        False       False
1        False       False      False  False         True       False
2        False       False      False  False        False       False
3        False       False      False  False         True       False
4        False       False      False  False         True       False
..         ...         ...        ...    ...          ...         ...
115      False       False      False  False        False       False
116      False       False      False  False         True       False
117      False       False      False  False         True       False
118      False       False      False  False        False       False
119      False       False      False  False        False       False

[120 rows x 6 columns]

In [33]:
df1.isna().sum()

record_id       0
patient_id      0
diagnosis       0
bp              0
sugar_level    35
visit_cost      0
dtype: int64

In [34]:
df1["sugar_level"]=df1["sugar_level"].fillna("0")
df1

    record_id patient_id     diagnosis      bp sugar_level  visit_cost
0        R101       P013  Hypertension  120/80       140.0        2000
1        R102       P105      Diabetes  120/80           0        2500
2        R103       P098  Hypertension    high       140.0        3000
3        R104       P038        Asthma  140/90           0        3000
4        R105       P040        Asthma  130/85           0        1500
..        ...        ...           ...     ...         ...         ...
115      R216       P081        Asthma    high       110.0        2500
116      R217       P033      Diabetes    high           0        1500
117      R218       P063  Hypertension  140/90           0        2000
118      R219       P011  Hypertension  130/85       180.0        2500
119      R220       P013  Hypertension    high       180.0        1500

[120 rows x 6 columns]